FROM node:alpine

# Set working directory
WORKDIR /app

RUN npm update -g npm@latest
RUN npm install --global pm2
RUN npm install -g next@latest

# Copy "package.json" and "package-lock.json" before other files
# Utilise Docker cache to save re-installing dependencies if unchanged
COPY ./package*.json ./

RUN npm install --silent --legacy-peer-deps

COPY .env .env
COPY ./ ./

ENV NODE_ENV=production
RUN npm run build

# Expose the listening port
EXPOSE 3000

# Run container as non-root (unprivileged) user
# The "node" user is provided in the Node.js Alpine base image
USER node

# Launch app with PM2
CMD [ "pm2-runtime", "start", "npm", "--", "start" ]